name: snwplugin
version: 0.0.4
authors: [JakeDaDream, RealInstantRamen, andyinnie, _Kastle laughed at me]
main: me.jakedadream.snwplugin.snwplugin
api-version: 1.16
commands:
  givecoin:
    description: Gives player a SNW coin
    usage: /<command>
  givestarcoin:
      description: Gives player a Star coin
      usage: /<command>
  mhat:
    description: Puts a model on your head
    usage: /<command> <number>
  mgive:
    description: Puts a model in your inventory
    usage: /<command> <number>
  idlist:
    description: Gives list of Model IDs
    usage: /<command>
  sc:
    description: Communicate to other staff
    usage: /<command> <message>
  gms:
    description: Changes your gamemode to Survival
    usage: /<command>
    aliases:
      - gm0
  gmc:
    description: Changes your gamemode to Survival
    usage: /<command>
    aliases:
      - gm1
  gmsp:
    description: Changes your gamemode to Survival
    usage: /<command>
    aliases:
      - gm3
  gma:
    description: Changes your gamemode to Survival
    usage: /<command>
    aliases:
      - gm2
  enderchest:
    description: Opens your EC
    usage: /<command>
    aliases:
      - ec
      - echest
      - enderc
  workbench:
    description: Opens a Workbench
    usage: /<command>
    aliases:
      - wb
      - craft
      - craftingtable
  invsee:
    description: Lets you see what another person has in their inventory
    usage: /<command> <player>
    aliases:
      - invpeek
      - invs
  Day:
    description: Sets the time to day
    usage: /<command>
    aliases:
      - setday
  Night:
    description: Sets the time to night
    usage: /<command>
    aliases:
      - setnight
  Noon:
    description: Sets the time to noon
    usage: /<command>
    aliases:
      - setnoon
  sex:
    description: You have sex
    usage: /<command>
  tp:
    description: Tp to another player or tp a player to another player
    usage: /<command> <player>
    aliases:
      - atp
  tphere:
    description: Tp's a player to you
    usage: /<command> <player>
    aliases:
      - atphere
  trashcan:
    description: Opens the trashcan inventory
    usage: /<command>
    aliases:
      - trash
  clearinventory:
    description: Clears your inventory
    usage: /<command>
    aliases:
      - ci
      - clearinv
      - clear
  fly:
    description: Allows you to toggle fly
    usage: /<command>
  Spawn:
    description: Brings you to spawn
    usage: /<command>
  skull:
    description: Give's you a player head
    usage: /<command> <player>
    aliases:
      - giveskull
      - skulls
      - head
  rename:
    description: Renames the item in your hand
    usage: /<command> <args>
  glow:
    description: Gives the item an enchantment effect
    usage: /<command>
    aliases:
      - glint
  unglow:
    description: Removes the item's enchantment effect
    usage: /<command>
    aliases:
      - unglint
  broadcast:
    description: Broadcast a message to everyone
    usage: /<command> <message>
    aliases:
      - bc
      - alert
      - messageall
  speed:
    description: changes how fast you move
    usage: /<command> <#>
  sudo:
    description: allows you to talk & run commands as others
    usage: /<command> <args>
  whomademe:
    description: tells you the creators of the plugin
    usage: /<command>
    aliases:
      - whoami
      - snwplugin
  rp:
    description: does rp stuff
    usage: /<command> <args>