name: snwplugin
version: 1.1
authors: [JakeDaDream, Lord_Of_Llamaz, RealInstantRamen]
main: me.jakedadream.snwplugin.snwplugin
api-version: 1.16
commands:
  givecoin:
    description: Gives player a SNW coin
    usage: /<command>
  givestarcoin:
      description: Gives player a Star coin
      usage: /<command>
  thruwand:
    description: Gives player a //thru wand
    usage: /<command>
  LlamazBanWand:
    description: Bans llamaz on right click
    usage: /<command>
  mhat:
    description: Puts a model on your head
    usage: /<command> <number>
  mgive:
    description: Puts a model in your inventory
    usage: /<command> <number>
  launch:
    description: Launches you in the air
    usage: /<command> <number>
  idlist:
    description: Gives list of Model IDs
    usage: /<command>
  sc:
    description: Communicate to other staff
    usage: /<command> <message>