name: JakesSNWPlugin
version: 1.1
authors: [JakeDaDream, Lord_Of_Llamaz, RealInstantRamen]
main: me.jakedadream.snwplugin.snwplugin
api-version: 1.16
commands:
  givecoin:
    description: Gives player a SNW coin
    usage: /<command>
  givestarcoin:
      description: Gives player a Star coin
      usage: /<command>
  thruwand:
    description: Gives player a //thru wand
    usage: /<command>
  LlamazBanWand:
    description: Bans llamaz on right click
    usage: /<command>
  mhat:
    description: Puts a model on your head
    usage: /<command> <number>
  mgive:
    description: Puts a model in your inventory
    usage: /<command> <number>
  launch:
    description: Launches you in the air
    usage: /<command> <number>
  idlist:
    description: Gives list of Model IDs
    usage: /<command>
  sc:
    description: Communicate to other staff
    usage: /<command> <message>
  gms:
    description: Changes your gamemode to Survival
    usage: /<command>
    aliases:
      - gm s
      - gm0
      - gm 0
  gmc:
    description: Changes your gamemode to Survival
    usage: /<command>
    aliases:
      - gm c
      - gm 1
      - gm1
  gmsp:
    description: Changes your gamemode to Survival
    usage: /<command>
    aliases:
      - gm sp
      - gm 3
      - gm3
  gma:
    description: Changes your gamemode to Survival
    usage: /<command>
    aliases:
      - gm a
      - gm 2
      - gm2
  nickname:
    description: Changes your display name
    usage: /<command> <name>
    aliases:
      - nick
  enderchest:
    description: Opens your EC
    usage: /<command>
    aliases:
      - ec
      - echest
      - enderc
  workbench:
    description: Opens a Workbench
    usage: /<command>
    aliases:
      - wb
      - craft
      - craftingtable
  invsee:
    description: Lets you see what another person has in their inventory
    usage: /<command> <player>
    aliases:
      - invpeek
      - invs
  invis:
    description: Gives you minecraft invis potion for 2 minutes
    usage: /<command>
    aliases:
      - giveinvis
      - setinvis
  uninvis:
    description: Removes potion effect Invis
    usage: /<command>
    aliases:
      - reminvis
      - removeinvis
      - unsetinvis